### ISSUE TITLE
Credstash AttributeError error after upgrading to 1.16.2

### ISSUE THREAD

**Issue by geoffbp** [fugue/credstash#273]
06:32:54 Traceback (most recent call last):
06:32:54   File "/home/jenkins-slave/workspace/Build/AMI/application-container-host-ami@17/viator-packer-venv/bin/credstash", line 5, in <module>
06:32:54     from credstash import main
06:32:54   File "/home/jenkins-slave/workspace/Build/AMI/application-container-host-ami@17/viator-packer-venv/bin/credstash.py", line 83, in <module>
06:32:54     setup_logging(logging.WARNING, 'credstash.log')
06:32:54   File "/home/jenkins-slave/workspace/Build/AMI/application-container-host-ami@17/viator-packer-venv/bin/credstash.py", line 73, in setup_logging
06:32:54     if logger.hasHandlers():
06:32:54 AttributeError: 'Logger' object has no attribute 'hasHandlers'

**Comment by vrgurus** [comment]
@geoffbp, I think is all related to same change made for logger. See #271

**Comment by eisjcormier** [comment]
what is the plan for fixing this or reverting the logging changes?

**Comment by mike-luminal** [comment]
Resolved by #279.
